### PR TITLE
Hint to -fno-gnu-unique

### PR DESCRIPTION
**Pull request by andreas-junghanns**

### CODE REVIEW

**Review by pmai — APPROVED** [review]
I have slightly expanded the guidance to better explain the nature of the problem and the potential interaction with e.g. RTLD_GLOBAL

**Comment by pmai** [comment]
@andreas-junghanns does this work for you?

**Comment by andreas-junghanns** [comment]
Yes, fine. I cannot hit "Approve" in this repo... maybe we should fix it so we can use the proper process?

**Comment by chrbertsch** [comment]
> Yes, fine. I cannot hit "Approve" in this repo... maybe we should fix it so we can use the proper process?

I think you cannot approve, because you created the PR. Can you merge?

**Pull request merged**
