### PR TITLE
Don't allow multiple instances if canBeInstantiatedOnlyOncePerProcess == false

### PR DESCRIPTION
**Pull request by t-sommer**

### CODE REVIEW

**Review by andreas-junghanns — CHANGES_REQUESTED** [review]
The "return NULL" is in contradiction to the current standard text: "These functions return a new instance of an FMU with the respective interface type. If a NULL pointer is returned, then instantiation failed."
I like the second part of the sentence - guarding against multiple instantiation if "not supported" is good practise (even if not easily done, because we cannot guarantee that certain codes have run before the second instantiation was called).

**Comment by pmai** [comment]
I don't see the contradiction to the standard though: If an FMU states that it can only be instantiated once per process, then I think failing to instantiate by returning NULL is what is called for...

**Comment by ghorwin** [comment]
I agree with Pierre. When a master tries to instatiate an FMU twice, though is states "canBeInstantiatedOnlyOncePerProcess = true", than this is a fault by the master. There are two ways to react: either, the FMU punishes the master for its fault by aboarting the process hard (call to terminate), or by gracefully returning a NULL pointer, hereby signaling the master that he made a mistake. If the master makes yet another error by not checking the pointer against NULL, the FMU can still check for NULL pointer itself in the upcoming init functions and there return an error - at latest at this point, the master should stop with an error.

For me, returning a NULL pointer would be sensible. Even with a valid pointer the outcome would be the same - i.e. error signaling from subsequent init functions. 

Lastly, the Master does never de-reference the returned pointer itself. So returning a NULL pointer should never result in a  segfault.

**Comment by andreas-junghanns** [comment]
Sorry, we need to tighten the language a bit, or others fall into the same trap I just crawl out of. I read your sentence as:
"FMUs with `canBeInstantiatedOnlyOncePerProcess == false` should return `NULL`; and provide an error message if an importer tries to create a second instance."
I read the "if" as only applying to the middle part of the sentence, that is.
Can we write:
"If an importer tries to create a second instance, then FMUs with `canBeInstantiatedOnlyOncePerProcess == false` should return `NULL` and provide an error message."?

**Review by andreas-junghanns — APPROVED** [review]
Now my parser also gets it, sorry.

**Pull request merged**
